<?php

return [
    '503' => ['nombre' => 'El Salvador', 'digitos' => 8],
    '1' => ['nombre' => 'Estados Unidos / Canadá', 'digitos' => 10],
    '502' => ['nombre' => 'Guatemala', 'digitos' => 8],
    '504' => ['nombre' => 'Honduras', 'digitos' => 8],
    '505' => ['nombre' => 'Nicaragua', 'digitos' => 8],
    '506' => ['nombre' => 'Costa Rica', 'digitos' => 8],
    '507' => ['nombre' => 'Panamá', 'digitos' => 8],
    '501' => ['nombre' => 'Belice', 'digitos' => 7],
    '52' => ['nombre' => 'México', 'digitos' => 10],
    '34' => ['nombre' => 'España', 'digitos' => 9],
    '57' => ['nombre' => 'Colombia', 'digitos' => 10],
    '58' => ['nombre' => 'Venezuela', 'digitos' => 10],
    '51' => ['nombre' => 'Perú', 'digitos' => 9],
    '56' => ['nombre' => 'Chile', 'digitos' => 9],
    '593' => ['nombre' => 'Ecuador'],
    '591' => ['nombre' => 'Bolivia'],
    '54' => ['nombre' => 'Argentina'],
    '55' => ['nombre' => 'Brasil'],
    '595' => ['nombre' => 'Paraguay'],
    '598' => ['nombre' => 'Uruguay'],
    '44' => ['nombre' => 'Reino Unido'],
    '49' => ['nombre' => 'Alemania'],
    '33' => ['nombre' => 'Francia'],
    '39' => ['nombre' => 'Italia'],
    '61' => ['nombre' => 'Australia'],
];
